name: Build and Deploy

on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Webiste
      run: |
        npm install
        ./node_modules/.bin/gatsby build --prefix-paths
    - name: Deploy Website
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
